# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Slug', models.SlugField(unique=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Country', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Governor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('MyStand', models.TextField(blank=True)),
                ('Slug', models.SlugField(unique=True)),
                ('Vote', models.BooleanField()),
                ('Twitter', models.URLField(blank=True)),
                ('Facebook', models.URLField(blank=True)),
                ('County', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.County')),
            ],
        ),
        migrations.CreateModel(
            name='MemberofCountyAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('MyStand', models.TextField()),
                ('Slug', models.SlugField(unique=True)),
                ('Vote', models.BooleanField()),
                ('Twitter', models.URLField()),
                ('Facebook', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Memberofparliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('MyStand', models.TextField()),
                ('Slug', models.SlugField(unique=True)),
                ('Vote', models.BooleanField()),
                ('Twitter', models.URLField()),
                ('Facebook', models.URLField()),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Slug', models.SlugField(unique=True)),
                ('Icon', models.ImageField(upload_to='')),
                ('Twitter', models.URLField()),
                ('Facebook', models.URLField()),
                ('Manifesto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('MyStand', models.TextField()),
                ('Slug', models.SlugField(unique=True)),
                ('Vote', models.BooleanField()),
                ('Twitter', models.URLField()),
                ('Facebook', models.URLField()),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Country')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Party')),
            ],
        ),
        migrations.CreateModel(
            name='RallyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('MyStand', models.TextField()),
                ('Slug', models.SlugField(unique=True)),
                ('Vote', models.BooleanField()),
                ('Twitter', models.URLField()),
                ('Facebook', models.URLField()),
                ('County', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.County')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Party')),
                ('RallyDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.RallyDate')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Slug', models.SlugField(unique=True)),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Constituency')),
            ],
        ),
        migrations.CreateModel(
            name='Womensrep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Middle_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Image', models.ImageField(upload_to='')),
                ('MyStand', models.TextField()),
                ('Slug', models.SlugField(unique=True)),
                ('Vote', models.BooleanField()),
                ('Twitter', models.URLField()),
                ('Facebook', models.URLField()),
                ('Constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Constituency')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Party')),
                ('RallyDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.RallyDate')),
            ],
        ),
        migrations.AddField(
            model_name='president',
            name='RallyDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.RallyDate'),
        ),
        migrations.AddField(
            model_name='memberofparliament',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Party'),
        ),
        migrations.AddField(
            model_name='memberofparliament',
            name='RallyDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.RallyDate'),
        ),
        migrations.AddField(
            model_name='memberofcountyassembly',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Party'),
        ),
        migrations.AddField(
            model_name='memberofcountyassembly',
            name='RallyDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.RallyDate'),
        ),
        migrations.AddField(
            model_name='memberofcountyassembly',
            name='Ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Ward'),
        ),
        migrations.AddField(
            model_name='governor',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Party'),
        ),
        migrations.AddField(
            model_name='governor',
            name='RallyDate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.RallyDate'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='County',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.County'),
        ),
    ]
