# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womensrep',
            name='Constituency',
        ),
        migrations.AddField(
            model_name='womensrep',
            name='County',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='vote.County'),
            preserve_default=False,
        ),
    ]
