# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20161017_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governor',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='memberofcountyassembly',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='memberofparliament',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='party',
            name='Icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='president',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='senator',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='womensrep',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
