# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20161022_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='president',
            name='height_field',
            field=models.IntegerField(default=290),
        ),
        migrations.AlterField(
            model_name='president',
            name='width_field',
            field=models.IntegerField(default=470),
        ),
    ]
